### PR TITLE
suggestions

### PR DESCRIPTION
**Pull request by sridhar-5**
Hey,

Check the comment I've made in readme man.

### CODE REVIEW

**Review by 2SpaceMasterRace — APPROVED** [review]
yeah I was just too tired to edit through them , now I'll add the finishing touches

**Comment by sridhar-5** [comment]
I understood. just wanted to make you see how a pull request looks on the other side.....xD.

**Comment by 2SpaceMasterRace** [comment]
can't believe I am bamboozled like that but it's super weird to accept pull requests and all lol 

also Hellloo from the other sidee

**Comment by sridhar-5** [comment]
Hi,....yes it's a nice experience.

**Pull request merged**
